run_name: bert-base-stage2-sbert
model_name: QuangDuy/bert-base-stage2-hf
output_dir: outputs/bert-base-stage2-sbert

train_dataset:
  - batmangiaicuuthegioi/zalo-legal-triplets
  - QuangDuy/mmarco-vi-hard-negatives
train_split: train
eval_dataset: another-symato/VMTEB-Zalo-legel-retrieval-wseg
eval_corpus_config: corpus
eval_queries_config: queries
eval_labels_config: data_ir
eval_split: train

eval_datasets:
  - dataset: taidng/UIT-ViQuAD2.0
    name: UIT-ViQuAD2.0
    format: squad
    split: validation
  - dataset: GreenNode/zalo-ai-legal-text-retrieval-vn
    name: Zalo-Legal
    corpus_config: corpus
    queries_config: queries
    labels_config: qrels
    split: test

seed: 42
max_seq_length: 4096
pooling: mean
normalize_embeddings: true
include_hard_negatives: true

num_train_epochs: 5
train_batch_size: 32
learning_rate: 5.0e-5
warmup_ratio: 0.1
weight_decay: 0.01
precision: bf16
use_amp: true
use_cached_mnrl: false

validation_size: 0.05
validation_subset: null
evaluation_steps: 4000
checkpoint_save_steps: 4000
checkpoint_save_total_limit: 5
early_stopping_patience: 4
hf_repo_id: QuangDuy/bert-base-stage2-sbert
hf_private: false
hf_push_on_save: true
run_retrieval_eval_after_train: true
retrieval_eval_limit_queries: null
retrieval_eval_extra_corpus_docs: null

matryoshka_dims:
  - 768
  - 512
  - 256
  - 128

truncate_dims:
  - 768
  - 512
  - 256
  - 128

top_k:
  - 1
  - 3
  - 5
  - 10

recall_at_k:
  - 5
  - 10
  - 100

map_at_k: 100
eval_batch_size: 64
